# Project information
site_name: Bedework Guide
site_url: https://nashville-public-library.github.io/bedework-docs/
site_description: Content creator and developer documentation for Nashville Public Library Bedework Enterprise Calendar.

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
  font: false

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg # Page tree

nav:
  - Introduction: index.md
  - Add Events:
      - add-events/title.md
      - add-events/date-time.md
      - add-events/recurrence-pattern.md
      - add-events/recurrence.md
      - add-events/description.md
      - add-events/status.md
      - add-events/cost.md
      - add-events/event-url.md
      - add-events/image.md
      - add-events/location.md
      - add-events/contact.md
      - add-events/topical-areas.md
      - add-events/series.md
      - add-events/public.md
      - add-events/closed.md
  - Image Library:
      - image-library/topic-logos.md
      - image-library/series-logos.md
      - image-library/organizations.md
      - image-library/wishing-chair-image-library.md
      - image-library/guest-performers.md
  - Using Images:
      - using-images/image-guidelines.md
      - using-images/finding-images.md
  - Orientation:
      - orientation/add-an-event.md
      - orientation/copy-event.md
      - orientation/edit-delete-event.md
      - orientation/get-to-bedework.md
  - Linking:
      - linking/custom.md
      - linking/address-bar.md
      - linking/generate-export-files.md
  - Admin:
      - admin/approving-events.md
      - admin/add-series.md
      - admin/cancel.md
      - admin/passwords.md
      - admin/reindex.md
      - admin/notifications.md
      - admin/theming.md
      - admin/training.md
      - admin/troubleshooting.md
      - admin/pixie-dust.md
copyright: c 2025 Metropolitan Government of Nashville and Davidson County, GNU GENERAL PUBLIC LICENSE.
